name: Build Project Backend

on:
  push:
    branches: ["backend/development", "backend/master"]
  pull_request:
    branches: ["backend/development", "backend/master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      # - name: Run tests
      #   run: npm test

      # - name: Push Docker image to Docker Hub
      #   uses: actions/push-docker-image-to-dockerhub@v1
      #   with:
      #     image_name: stellar-drive
      #     image_tag: latest
      #     dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      #     dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
      #     registry: docker.io
      #     repository: cloudcw/cloud_cw
      #     tag_with_sha: true

      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_PASSWORD }}/stellar-drive .
          docker push ${{ secrets.DOCKER_PASSWORD }}/stellar-drive
