name: Build Project Backend

on:
  push:
    branches: ["backend/development", "backend/master"]
  pull_request:
    branches: ["backend/development", "backend/master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Retrieve Docker login credentials
        run: echo "${{ secrets.DOCKER_CREDENTIALS }}" > docker-credentials.txt

      - name: Login to Docker
        run: docker login -u "$(cat docker-credentials.txt | jq -r '.username')" -p "$(cat docker-credentials.txt | jq -r '.password')"

      - name: Build Docker Image
        run: docker build -t stellar-drive .

      - name: change image tag
        run: docker tag $(docker images -q stellar-drive) cloudcw/stellar-drive:2.3

      - name: Push Docker image to Docker Hub
        run: docker push cloudcw/stellar-drive:2.3
