name: Build Project Backend

on:
  push:
    branches: ["backend/development", "backend/master"]
  pull_request:
    branches: ["backend/development", "backend/master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      # - name: Run tests
      #   run: npm test

      # - name: Push Docker image to Docker Hub
      #   uses: actions/push-docker-image-to-dockerhub@v1
      #   with:
      #     image_name: stellar-drive
      #     image_tag: latest
      #     dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      #     dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
      #     registry: docker.io
      #     repository: cloudcw/cloud_cw
      #     tag_with_sha: true
      - name: Retrieve Docker login credentials
        run: echo "${{ secrets.DOCKER_CREDENTIALS }}" > docker-credentials.txt

      - name: Login to Docker
        run: docker login -u "$(cat docker-credentials.txt | jq -r '.username')" -p "$(cat docker-credentials.txt | jq -r '.password')"

      - name: Build Docker Image
        run: |
          docker build -t stellar-drive .
          IMAGE_ID=$(docker build -t my-image . --format '{{.ID}}')
          echo "Image ID: $IMAGE_ID"
          echo "::set-output name=image_id::$IMAGE_ID"

      - name: change image tag
        run: docker tag ${{ steps.build.outputs.image_id }} cloudcw/stellar-drive:Updated

      - name: Push Docker image to Docker Hub
        run: docker push cloudcw/stellar-drive:Updated

      # - name: Build and push Docker image
      #   run: |
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker build -t ${{ secrets.DOCKER_PASSWORD }}/stellar-drive .
      #     docker push ${{ secrets.DOCKER_PASSWORD }}/stellar-drive:latest
