name: Build Project Backend

on:
  push:
    branches: [ "backend/development", "backend/master" ]
  pull_request:
    branches: [ "backend/development", "backend/master" ]

jobs:
  job_1:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      # - name: Run tests
      #   run: npm test



jobs:
  job_2:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: cloudcw/cloud_cw
          tag_with_sha: true
